apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mlops-streamlit-ui.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mlops-streamlit-ui.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mlops-streamlit-ui.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mlops-streamlit-ui.name" . }}
    spec:
      containers:
        - name: streamlit
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8501
              name: http
          env:
            - name: API_URL
              value: {{ .Values.env.API_URL | quote }}
            - name: APP_VERSION
              value: {{ .Values.env.APP_VERSION | quote }}
          resources:
{{ toYaml .Values.resources | indent 12 }}

          {{- if .Values.probes.enabled }}
          readinessProbe:
            httpGet:
              path: /
              port: 8501
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
          livenessProbe:
            httpGet:
              path: /
              port: 8501
            initialDelaySeconds: {{ add .Values.probes.initialDelaySeconds 10 }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
          {{- end }}
